version: '3'
services:
  mypostgres:
    image: 'postgres:latest'
    ports:
      - "5430:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: kishore  
  claimserviceapi-container:
    build: .
    ports:
      - "8080:8080"
    depends_on:
    - mypostgres    
